//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_Ultima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int Id { get; set; }
        public string Nombre_Receta { get; set; }
        public string Pais { get; set; }
        public string Ingrediente1 { get; set; }
        public string Ingrediente2 { get; set; }
        public string Ingrediente3 { get; set; }
        public string Preparacion { get; set; }
        public string Cantidad_Personas { get; set; }
    }
}
